### PR TITLE
Handle additional tumblr urls and protect against pugme returning HTML

### PR DESCRIPTION
**Pull request by Pezmc**
There appear to be two different formats now:
1. `http://30.media.tumblr.com/tumblr_lsx4nsg5Hj1qa25vco1_500.jpg`
2. `http://41.media.tumblr.com/95a84579fa297844891b3ab1a5c76c0a/tumblr_mooibbcKl51rylzllo1_500.jpg`
This change adds support for the optional directory before the image file.

Additionally the pugme service appears to occasionally return html rather than a url, e.g. 
`http://30.media.tumblr.com/tumblr_lsx4nsg5Hj1qa25vco1_500.jpg"/><br/><br/><img
src="http://28.media.tumblr.com/tumblr_lsx4nsg5Hj1qa25vco8_500.jpg`
The change grabs the first url only from the pugme input

Note: this PR includes my previous PR's as it was forked from that branch

### CODE REVIEW

**Comment by Pezmc** [comment]
I'll stop now ;-)

**Comment by adunkman** [comment]
Hah, I never got back to this. :p

**Comment by adunkman** [comment]
Looks good to me! 

aww yiss 

Thanks!

**Comment by Pezmc** [comment]
jim-carrey

**Pull request merged**
